### Downloading dataset and extracting data

In [0]:
## Download the dataset
import urllib.request
# "https://archive.ics.uci.edu/ml/machine-learning-databases/20newsgroups-mld/20_newsgroups.tar.gz"

urllib.request.urlretrieve ("https://archive.ics.uci.edu/ml/machine-learning-databases/20newsgroups-mld/20_newsgroups.tar.gz", "a.tar.gz")

('a.tar.gz', <http.client.HTTPMessage at 0x7f157ce754e0>)

In [0]:
#Extracting the dataset
import tarfile
tar = tarfile.open("a.tar.gz")
tar.extractall()
tar.close()

### Import Statements
- sklearn => for different metrics, train-test splitting and sklearn's Naive Bayes implementation
- nltk => not used

In [0]:
# Importing required libraries
import pandas as pd
import numpy as np
import os
import string, re
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

In [0]:
# Stop words - generally to be avoided
stop_words = ['will', 'werent', 'whom', 'un', 'seem', 'contains', 'just', 'briefly', 'whither', 'meantime', 'shown', 'largely', 'nearly', 'corresponding', 'nobody', 'such', 'specifically', 'saying', 'changes', 'appropriate', 'arise', 'inasmuch', 'regardless', 'taken', 'wish', 'consequently', 'alone', "they'll", 'not', 'rather', 'thickv', 'th', 'one', 'quickly', 'hed', 'doing', 'selves', 'besides', 'once', 'latterly', 'act', 'example', 'he', 'namely', 'hasn', 'research', 'most', 'needn', 'nevertheless', 'both', 'necessarily', 's', 'never', 'next', 'hello', 'keep', "c'mon", 'inc', 'date', 'don', 'away', 'have', 'mrs', 'placed', "let's", 'despite', 'etc', "should've", 'anywhere', 'whole', "you'd", "there've", 'followed', 'beginnings', 'recently', 'formerly', 'does', 'liked', 'seeing', 'we', 'am', 'ref', 'actually', 'hither', 'containing', 'after', 'hadn', 'self', 'beside', 'everywhere', 'help', 'shouldn', 'third', 'likely', 'shes', 'wed', 'available', 'there', 'won', 'second', 'twelve', 'happens', 'went', 'sure', 'the', 'right', 'throug', 'perhaps', 'took', 'further', "mightn't", 'see', 'aside', 'edu', 'r', 'thats', "i'd", 've', 'obviously', 'amongst', 'ever', "i'm", 'indicated', 'isn', 'merely', "ain't", "shouldn't", 'cause', 'kept', 'in', 'now', 'together', 'q', 'line', 'always', 'doesn', 'moreover', 'on', 'move', 'successfully', 'say', 'causes', 'usually', 'still', 'those', 'hundred', 'has', 'okay', 'like', 'ending', 'mostly', 'else', 'ran', 'didn', 'over', 'definitely', 'thoroughly', 'theirs', 'out', 'how', 'overall', 'least', 'try', 'for', 'anyone', 'regarding', 'interest', "they're", 'certain', 'having', 'slightly', 'indicates', 'accordance', 'already', 'seven', 'toward', 'ninety', 'viz', 'ie', 'had', 'normally', 'several', 'welcome', 'youd', 'eg', 'mg', 'more', "a's", 'however', 'noted', 'old', 'much', 'qv', 'whereby', 'thank', 'considering', 'theres', 'appreciate', 'give', 'immediately', 'nowhere', 'couldn', 'respectively', 'n', 'e', 'via', 'three', 'onto', 'better', 'says', 'secondly', 'hardly', 'call', 'h', 'sec', 'got', 'sub', 'o', 'me', 'present', "it'll", 'being', 'inner', 'first', 'currently', 'various', 'want', 'wouldn', 'plus', 'last', 'mine', 'resulted', 'top', 'sufficiently', 'do', 'whereafter', 'any', 'reasonably', 'six', 'done', 'consider', 'immediate', 'detail', 'same', 'approximately', 'hi', 'indeed', 'ex', 'km', 'possible', 'wants', 'vols', 'k', 'able', 'sent', 'especially', 'invention', 'whereupon', 'off', 'p', 'upon', 'mightn', 'provides', 'shows', 'twice', 'hers', 'although', 'showed', 'tip', 'she', 'when', 'by', 'obtained', 'soon', 'appear', 'affects', 'gets', 'owing', 'former', 'associated', "we're", 'quite', 'abst', "we've", 'knows', 'part', 'theyre', 'elsewhere', 'latter', 'haven', 'across', 'per', 'whats', 'about', 'recent', 'lest', 'results', 'towards', 'course', 'they', 'significantly', 'eight', 'than', 'afterwards', "it's", 'youre', 'itself', 'readily', 'refs', 'specified', 'w', "where's", 'downwards', 'during', 'whereas', 'serious', 'amount', 'between', 'begin', 'whose', "there'll", 'v', 'bottom', 'vs', "aren't", 'that', 'near', 'specify', 'section', 'ask', 'keeps', "'ll", 'mustn', 'front', 'presumably', 'beginning', 'somewhat', 'de', 'go', 'necessary', 'fire', "you'll", 'seriously', 'somethan', 'promptly', 'thereafter', 'z', 'sincere', "can't", 'specifying', 'while', 'hes', 'particular', 'wasnt', "how's", 'anything', 'amoungst', 'yes', 'page', 'past', "'ve", 'thousand', 'inward', 'with', 'anyways', 'contain', 'potentially', 'within', 'everything', 'her', 'end', 'other', 'describe', 'comes', 'et', 'these', 'fix', 'thanx', 'cannot', 'its', 'importance', "won't", 'added', 'very', 'thru', 'getting', "you're", 'thin', "he's", "don't", 'looks', 'forty', 'tell', 'somehow', 'indicate', 'own', 'would', 'thereto', 'ones', 'otherwise', 'known', 'd', 'probably', 'itd', 'made', 'follows', 'l', "you've", 'yourself', 'm', 'nd', 'taking', 'ff', 'only', 'though', 'everyone', 'b', 'whomever', 'who', 'but', 'all', 'almost', 'run', 'world', 'insofar', 'resulting', 'unlike', 'none', 'ma', "he'd", "she'll", 'wherever', 'anybody', 'must', 'apart', 'greetings', 'hopefully', 'into', 'kg', 'widely', 'significant', 'www', 'think', 'index', 'around', 'came', 'going', 'no', 'instead', 'others', 'nine', 'really', 'or', 'novel', 'mean', 'relatively', 'noone', 'herself', 'whos', 'well', 'aren', 'enough', 'lets', 'behind', 'back', 'need', 'of', 'yours', 'put', 'hereupon', 'and', 'using', 'something', 'whether', 'thanks', 'another', 'fifteen', 'what', 'weren', 'million', 'affected', 'two', 'why', 'obtain', 'empty', 'twenty', 'himself', 'oh', "when's", 'nonetheless', "we'd", 'ought', "isn't", 'show', 'your', 'herein', 'ignored', 'whatever', 'every', 'later', 'showns', 'before', "they'd", "what'll", 'f', "couldn't", 'here', 'rd', 'brief', "didn't", "she's", 'awfully', 'system', 'since', 'up', 'often', 'given', "what's", 'primarily', 'gave', 'best', 'needs', 'furthermore', 'thereof', "wasn't", 'seen', 'shed', 'theyd', 'usefully', 'against', 'so', 'particularly', 'til', 'fify', 'his', 'biol', "here's", "i've", "haven't", 'effect', 'became', 'nor', 'tried', 'also', 'sensible', 'know', 'ok', 'clearly', 'na', 'substantially', 'beyond', 'without', 'ca', 'new', 'certainly', 'which', 'myself', 'uses', 'tries', 'if', 'some', 'anyhow', "who'll", 'whoever', 'might', 'either', 'each', 'possibly', 'suggest', 'sixty', 'under', "she'd", 'thereupon', 'wheres', 'please', 'many', "wouldn't", 'according', 'be', 'co', 'sometimes', 'five', 'can', 'described', 'among', 'therein', 'our', 'useful', 'below', 'y', 'howbeit', 'que', 'even', 'them', 'nay', 'side', 'thou', 'similarly', 'until', 'found', 'willing', 'mainly', 'him', "that've", 'let', 'except', 'wont', 'zero', 'goes', 'eleven', 'fifth', "mustn't", 'is', 'yourselves', 'hid', 'four', 'somebody', "there's", 'tends', 'thorough', 'again', 'did', 'thereby', 'adj', 'gone', 'nothing', 'com', 'sometime', 'con', 'full', "needn't", 'heres', 'pages', 'may', 'value', 'cry', 'accordingly', 'previously', 'it', 'words', 'then', 'hereafter', 'allow', 'at', 'look', 'x', "hadn't", 'neither', 'wherein', 'you', "why's", 'was', 'u', 'fill', 't', 'important', 'throughout', 'this', 'ups', 'information', 'announce', 'their', 'apparently', 'wasn', 'g', 'someone', 'because', "shan't", 'shan', 'auth', 'trying', 'forth', 'ed', 'truly', 'way', "he'll", 'miss', 'i', 'lately', 'from', 'allows', 'name', 'exactly', 'above', 'ml', 'usefulness', 'were', 'could', 'down', 'wonder', 'poorly', 'concerning', 'ts', "doesn't", 'similar', 'home', 're', 'non', 'as', 'gotten', 'vol', 'yet', 'entirely', 'my', 'whenever', 'take', 'use', 'maybe', 'ltd', 'means', 'find', 'whence', 'far', 'shall', "t's", 'seems', 'looking', 'cant', 'id', "they've", 'to', 'thoughh', 'hereby', 'couldnt', 'unless', "we'll", 'im', 'little', 'mug', 'strongly', 'regards', "c's", 'less', 'sorry', 'arent', 'begins', 'becoming', 'thus', 'meanwhile', 'pp', 'become', "i'll", 'affecting', 'unfortunately', 'somewhere', 'seeming', 'ten', 'themselves', 'unlikely', "that'll", 'whim', 'gives', 'due', 'proud', 'll', 'c', 'makes', 'giving', 'saw', 'unto', 'related', 'ours', 'too', 'come', 'following', 'becomes', 'eighty', 'predominantly', 'ain', 'mill', 'therere', 'been', 'hasnt', 'used', 'everybody', 'ord', 'anymore', 'ah', 'make', 'an', 'different', 'get', 'said', 'thence', 'bill', 'are', 'beforehand', 'stop', 'therefore', 'a', 'thered', "weren't", 'j', 'nos', 'outside', 'along', 'asking', 'omitted', 'where', 'us', 'whod', 'should', 'anyway', "hasn't", "who's", "it'd", 'seemed', 'wouldnt', 'sup', 'ourselves', 'through', 'mr', 'few', 'hence', 'believe', "that's"]
stop_words = set(stop_words)


# Block words - words to be avoided specific to the dataset
block_words = ['newsgroups', 'xref', 'path', 'from', 'subject', 'sender', 'organisation', 'apr','gmt', 'last','better','never','every','even','two','good','used','first','need','going','must','really','might','well','without','made','give','look','try','far','less','seem','new','make','many','way','since','using','take','help','thanks','send','free','may','see','much','want','find','would','one','like','get','use','also','could','say','us','go','please','said','set','got','sure','come','lot','seems','able','anything','put', '--', '|>', '>>', '93', 'xref', 'cantaloupe.srv.cs.cmu.edu', '20', '16', "max>'ax>'ax>'ax>'ax>'ax>'ax>'ax>'ax>'ax>'ax>'ax>'ax>'ax>'ax>'", '21', '19', '10', '17', '24', 'reply-to:', 'thu', 'nntp-posting-host:', 're:','25''18'"i'd"'>i''22''fri,''23''>the','references:','xref:','sender:','writes:','1993','organization:']
block_words = set(block_words)

### Extracting actual data from files

In [0]:
# get data in which x has paths of files and y has labels in numeric format
def get_data():
    path_all_folders = './20_newsgroups'

    path_folders = os.listdir(path_all_folders)

    d = {}
    for i in range(len(path_folders)):
        d[path_folders[i]] = i
    
    x = []
    y = []


    for i in range(len(path_folders)):
        newsgroup_name = path_folders[i]

        path_folders[i] = os.path.join(path_all_folders, path_folders[i])

        files = os.listdir(path_folders[i])
        for j in range(len(files)):
            x.append(os.path.join(path_folders[i], files[j]))
            y.append(d[newsgroup_name])

    x = np.array(x)
    y = np.array(y)
    return x, y

In [0]:
# get data and split the data
x, y = get_data()
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((15997,), (4000,), (15997,), (4000,))

### Extracting meaningful words from data

In [0]:
# cleans one line 
def clean_text(line, stop_words, block_words):
    words = line.split()
    clean_words = []
    
    # removes punctuations and digits
    punctuation = string.punctuation + '0123456789'
    table = str.maketrans('', '', punctuation)
    
    for word in words:
        word = word.lower()
        translated = word.translate(table)
        
        if word not in stop_words and translated not in stop_words and (
                                                    word not in block_words and translated not in block_words) and len(word) > 2: 
            word = translated
            if word == '':
                continue
            clean_words.append(word)
            
    return clean_words

In [0]:
# returns the desirable words from the text
def get_words(text, stop_words, block_words):
    lines = text.split('\n')[10:]
    
    words = []
    
    for line in lines:
        cleaned_text = clean_text(line.strip(), stop_words, block_words)
        words.extend(cleaned_text)
        
    return words

In [0]:
# makes dictionary
def make_dict(words, d=None):
    if d is None:
        d = dict()
    for word in words:
        d[word] = d.get(word, 0) + 1
    return d

In [0]:
# returns two dictionaries - one for columns/features another for making dataset
def get_dictionary_of_file(x_train, stop_words, block_words):
    combined_dictionary = {}
    individual_dictionaries = {}
    
    for x in x_train:
        f = open(x, errors='ignore')
        document = f.read()
        words = get_words(document, stop_words, block_words)
        make_dict(words, combined_dictionary)
        individual_dictionary = {}
        make_dict(words, individual_dictionary)
        
        individual_dictionaries[x] = individual_dictionary
        
    return combined_dictionary, individual_dictionaries

In [0]:
# preprocessing for train
def preprocess(x_train, y_train, stop_words, block_words):
    cd, ids = get_dictionary_of_file(x_train, stop_words, block_words)
        
    features = np.array(sorted(cd.items(), key=lambda x: x[1], reverse=True)[:3000])
    
    df = pd.DataFrame(columns=features[:, 0])
    df.insert(len(df.columns), 'LABEL', 0, allow_duplicates = False)
    
    
    i = 0

    for x in x_train:
        df.loc[i] = 1
        df.loc[i, 'LABEL'] = y_train[i]
        individual_dictionary = ids[x]
        for k, v in individual_dictionary.items():
            if k in df.columns:
                df.loc[i, k] += v
        i += 1
        if i % 1000 == 0:
          print(i)
    
    return df

In [0]:
df = preprocess(x_train, y_train, stop_words, block_words)

1000


In [0]:
# preprocessing for test - different from train (because now the features are known)
def preprocess_test(x_test, y_test, df, stop_words, block_words):
    individual_dictionaries = {}
    
    for x in x_test:
        f = open(x, errors='ignore')
        document = f.read()
        words = get_words(document, stop_words, block_words)

        individual_dictionary = {}
        make_dict(words, individual_dictionary)
        
        individual_dictionaries[x] = individual_dictionary

    i = 0
    df_test = pd.DataFrame()
    
    for col_name in df.columns:
        df_test.insert(len(df_test.columns), col_name, 0, allow_duplicates = False)
    
    for x in x_test:
        df_test.loc[i] = 1
        df_test.loc[i, 'LABEL'] = y_test[i]
        individual_dictionary = individual_dictionaries[x]
        for k, v in individual_dictionary.items():
            if k in df_test.columns:
                df_test.loc[i, k] += v
        i += 1
        if i % 1000 == 0:
          print(i)
    
    return df_test

In [0]:
df_test = preprocess_test(x_test, y_test, df, stop_words, block_words)

100
200
300
400


### Sklearn Multinomial Naive Bayes Implementation

In [0]:
clf = MultinomialNB()
clf.fit(df.iloc[:, :-1], df.iloc[:, -1])
clf.score(df.iloc[:, :-1], df.iloc[:, -1])

0.55625

In [0]:
sklearn_score = clf.score(df_test.iloc[:, :-1], df_test.iloc[:, -1])
sklearn_score

0.4175

In [0]:
print(confusion_matrix(y_pred=clf.predict(df_test.iloc[:, :-1]), y_true=y_test))

[[ 1  0  0  0  0  2  0  0  0  3  9  0  0  0  1  0  0  0  0  1]
 [ 0 15  0  0  0  0  0  1  0  0  6  0  0  0  0  0  0  0  0  0]
 [ 0  0 11  3  0  3  0  0  0  0  4  0  0  0  0  0  0  0  0  0]
 [ 0  0  3 10  0  3  0  0  1  0  4  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  0  0  0  0  3  8  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0 20  0  0  0  0  1  0  0  0  1  0  0  0  0  0]
 [ 0  1  0  0  0  6 10  0  1  0  2  0  0  0  0  0  0  0  0  1]
 [ 0  0  1  0  0  3  0  7  5  0  1  0  0  1  0  0  0  0  0  0]
 [ 0  0  1  0  0  1  0  2 10  0  2  0  0  1  0  2  0  1  0  0]
 [ 0  0  0  0  0  2  0  0  0  5  8  0  0  0  2  0  0  0  0  2]
 [ 0  0  0  0  0  2  0  0  0  1 16  0  0  0  1  0  0  0  0  1]
 [ 0  1  0  0  0  6  0  1  1  0  3  7  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  4  0  0  0  0 15  0  2  0  1  0  0  0  0  2]
 [ 0  0  0  0  0  4  0  0  2  0  2  0  0  5  0  0  0  0  2  0]
 [ 0  0  0  0  0  1  0  0  0  1  4  0  0  0 12  0  0  0  0  3]
 [ 0  0  0  0  0  4  0  0  3  0  6  0  0  0  0  5  0  0

### Custom Multinomial Naive Bayes Implementation 

In [0]:
# Converting dataframe to numpy arrays for custom implementation
data_train = df.values[:, :-1]
labels_train = df.values[:, -1]
data_test = df_test.values[:, :-1]
labels_test = df_test.values[:, -1]

In [0]:
counts = {}
labels = np.unique(labels_train)
num_features = data_train.shape[1]

In [0]:
## Fitting the data - creating a dictionary to keep frequency of words
def fit(x, y):
    labels = np.unique(y)
    num_features = x.shape[1]
    counts = {}
    counts['total_count'] = 0
    
    for label in labels:
      counts[label] = dict()
      total = 0

      for feature in range(num_features):
        val = ((x[y == label])[:, feature]).sum()
        total += val
        counts[label][feature] = val
        counts['total_count'] += val

      counts[label]['total_count'] = total

    return counts

In [0]:
counts = fit(data_train, labels_train)

In [0]:
## Function to predict the test data
def predict(x_test, counts): 
    predictions = []
    labels = np.unique(labels_train)
    num_features = data_train.shape[1]
    
    for row in x_test:
      max_pr = float('-inf')
      prediction = -1
      probability = 0
      
      for label in labels:
        probability = np.log(counts[label]['total_count']) - np.log(counts['total_count'])
        
        for feature in range(num_features):
          probability += row[feature]*(np.log(counts[label][feature]) - np.log(counts[label]['total_count']))

        if probability > max_pr:
          max_pr = probability
          prediction = label

      predictions.append(prediction)
      
    return predictions

In [0]:
y_pred = predict(data_test, counts)

In [0]:
print(classification_report(y_pred = y_pred, y_true = labels_test))

              precision    recall  f1-score   support

           0       1.00      0.06      0.11        17
           1       0.79      0.68      0.73        22
           2       0.69      0.52      0.59        21
           3       0.77      0.48      0.59        21
           4       1.00      0.14      0.25        14
           5       0.26      0.91      0.41        22
           6       1.00      0.48      0.65        21
           7       0.58      0.39      0.47        18
           8       0.40      0.50      0.44        20
           9       0.31      0.26      0.29        19
          10       0.14      0.76      0.24        21
          11       1.00      0.37      0.54        19
          12       1.00      0.04      0.07        26
          13       0.38      0.33      0.36        15
          14       0.52      0.57      0.55        21
          15       0.71      0.28      0.40        18
          16       0.92      0.41      0.57        29
          17       0.67    

In [0]:
custom_score = accuracy_score(y_pred = y_pred, y_true = labels_test)
custom_score

In [0]:
print(confusion_matrix(y_pred = y_pred, y_true = labels_test))

[[ 1  0  0  0  0  2  0  0  0  3  9  0  0  0  1  0  0  0  0  1]
 [ 0 15  0  0  0  0  0  1  0  0  6  0  0  0  0  0  0  0  0  0]
 [ 0  0 11  3  0  3  0  0  0  0  4  0  0  0  0  0  0  0  0  0]
 [ 0  0  3 10  0  3  0  0  1  0  4  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  0  0  0  0  3  8  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0 20  0  0  0  0  1  0  0  0  1  0  0  0  0  0]
 [ 0  1  0  0  0  6 10  0  1  0  2  0  0  0  0  0  0  0  0  1]
 [ 0  0  1  0  0  3  0  7  5  0  1  0  0  1  0  0  0  0  0  0]
 [ 0  0  1  0  0  1  0  2 10  0  2  0  0  1  0  2  0  1  0  0]
 [ 0  0  0  0  0  2  0  0  0  5  8  0  0  0  2  0  0  0  0  2]
 [ 0  0  0  0  0  2  0  0  0  1 16  0  0  0  1  0  0  0  0  1]
 [ 0  1  0  0  0  6  0  1  1  0  3  7  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  4  0  0  0  0 15  0  1  0  1  0  0  0  0  3]
 [ 0  0  0  0  0  4  0  0  2  0  2  0  0  5  0  0  0  0  2  0]
 [ 0  0  0  0  0  1  0  0  0  1  4  0  0  0 12  0  0  0  0  3]
 [ 0  0  0  0  0  4  0  0  3  0  6  0  0  0  0  5  0  0

### Comparison between Sklearn's Multinomial Naive Bayes and Custom Implementation of Multinomial Naive Bayes

In [0]:
print("Accuracy for sklearn MultinomialNB() - ", sklearn_score)
print("Accuracy for self-implemented Naive Bayes - ", custom_score)